### PR TITLE
Merge comlete playlist generated page into main branch

### PR DESCRIPTION
**Pull request by justbru**
I finalized the CSS for this page, added playlist title and description, and a like and share button. The like button needs to be attached to a backend call to add to users liked playlists, but the share button likes the playlist within the user's account (this function works).

### CODE REVIEW

**Review by Kraetiv — APPROVED** [review]
Looks good to me.  Just a bit confused on what 'likePlaylistToSpotify' does.

**Comment by justbru** [comment]
> Looks good to me. Just a bit confused on what 'likePlaylistToSpotify' does.

This function likes the playlist directly into the user's spotify, whereas likePlaylist likes the playlist into our database.

**Comment by piinabisket** [comment]
Everything looks good, should like and share functionality be switched around?

**Comment by justbru** [comment]
> 

I dont think so. Like button likes to our database and share likes it to spotify. I could be misunderstanding but this makes the most sense to me

**Comment by justbru** [comment]
> Everything looks good, should like and share functionality be switched around?

I don't think so. Like button likes to our database and share likes it to Spotify. I could be misunderstanding but this makes the most sense to me

**Pull request merged**
